seed_everything: true
trainer:
  enable_checkpointing: true
  accelerator: auto
  # strategy: auto
  num_nodes: 1
  devices:
  - 1
  - 2
  - 3
  fast_dev_run: false
  max_epochs: 100000
  precision: 32
  sync_batchnorm: false
  inference_mode: true
  use_distributed_sampler: true
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 1
model:
  dataset_type: raindrop_real
  train_datasets: /home/csx/data/RainDS/RainDS_real
  train_bs: 36
  test_datasets: null
  test_bs: 7
  val_datasets: /home/csx/data/RainDS/RainDS_real
  val_bs: 6
  initlr: 0.0007
  weight_decay: 0.01
  crop_size: 128
  crop_size_test: 128
  num_workers: 2
ckpt_path: null 
